## Portugu√™s üáßüá∑

# Lidando com erros em opera√ß√µes ass√≠ncronas

### No √∫ltimo exerc√≠cio, usamos em conjunto `callbacks` e assincronicidade, que nesse caso correspondem a:
- opera√ß√£o ass√≠ncrona : retorno de `user` depois de um certo tempo, que varia;
- callbacks : as fun√ß√µes `userFullName` e `userNationality`, que s√£o chamadas depois que o usu√°rio √© retornado.

### Nesse caso, a opera√ß√£o ass√≠ncrona sempre finaliza com sucesso, e existe uma callback que atua sobre o resultado desse sucesso. Mas isso n√£o reflete por completo todas as opera√ß√µes ass√≠ncronas.
<br>

### Suponhamos que estejamos pegando dados de usu√°rio via requisi√ß√£o em um outro servidor. Podemos garantir que essa requisi√ß√£o vai ocorrer sempre com sucesso? E se houver uma falha de conex√£o? E se o servidor n√£o estiver funcionando no momento da requisi√ß√£o? Esses casos s√£o exemplos de fatores externos, sobre os quais n√£o se tem controle algum e que precisam ser tratados.
<br>

### Ou seja, da mesma forma que se tem uma `callback` para quando a opera√ß√£o ass√≠ncrona tem sucesso, tamb√©m precisaria ter uma callback para quando a opera√ß√£o ass√≠ncrona termina com erro.
